// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaabenbogenProvider.Data;

#nullable disable

namespace VaabenbogenProvider.Migrations
{
    [DbContext(typeof(VaabenBogenContext))]
    partial class VaabenBogenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VaabenbogenProvider.Models.Jaeger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Foedselsdato")
                        .HasColumnType("date");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JaegerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobil")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jaegere");
                });

            modelBuilder.Entity("VaabenbogenProvider.Models.Vaaben", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fabrikat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("JaegerId")
                        .HasColumnType("integer");

                    b.Property<string>("Ladefunktion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Loebenummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VirksomhedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JaegerId");

                    b.HasIndex("VirksomhedId");

                    b.ToTable("Vaaben");
                });

            modelBuilder.Entity("VaabenbogenProvider.Models.Virksomhed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cvr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDato")
                        .HasColumnType("date");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDato")
                        .HasColumnType("date");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Virksomheder");
                });

            modelBuilder.Entity("VaabenbogenProvider.Models.Vaaben", b =>
                {
                    b.HasOne("VaabenbogenProvider.Models.Jaeger", null)
                        .WithMany("TilknyttedeVaaben")
                        .HasForeignKey("JaegerId");

                    b.HasOne("VaabenbogenProvider.Models.Virksomhed", null)
                        .WithMany("TildelteVaaben")
                        .HasForeignKey("VirksomhedId");
                });

            modelBuilder.Entity("VaabenbogenProvider.Models.Jaeger", b =>
                {
                    b.Navigation("TilknyttedeVaaben");
                });

            modelBuilder.Entity("VaabenbogenProvider.Models.Virksomhed", b =>
                {
                    b.Navigation("TildelteVaaben");
                });
#pragma warning restore 612, 618
        }
    }
}
