name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish -c Release -o publish
      

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: published-app
          path: publish/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: published-app
          path: publish/

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVICE_NAME: "vaabenbogen.service"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -r publish/* $SERVER_USER@$SERVER_IP:/home/ubuntu/VaabenbogenConsumer_1_0/
          ssh -i private_key $SERVER_USER@$SERVER_IP << EOF
            sudo systemctl restart $SERVICE_NAME
            sudo systemctl status $SERVICE_NAME --no-pager
          EOF
